### ISSUE TITLE
Communications between connected devices

### ISSUE THREAD

**Issue by eschumacher** [govert/WiFiDirectLegacyAPDemo#2]
Once a client has connected to the legacyAP, I am unable to ping between client and legacyAP.  I see the client connect and it appears that each device has an IP assigned within the same subnet, but pinging times out.

Is there another step missing that allows for communication between connected devices?

**Comment by govert** [comment]
I can't remember whether ping was working, but I could load a web page that was hosted on the AP machine.
You might try to disable the firewall as a first test to see if it might be blocking the pings - I think blocking pings is the current default.

**Comment by eschumacher** [comment]
Thank you so much for the quick response.  Yes you are correct, ssh and http traffic looks to be working so something on Windows' side must be blocking the ping.

Extremely appreciative for the quick response, as well as the cloned example and prebuilt binary.
