### ISSUE TITLE
Custom IP settings

### ISSUE THREAD

**Issue by Moret84** [govert/WiFiDirectLegacyAPDemo#5]
Hello, thanks for the tool that works flawlessly.
It always use 192.168.137.1 as base IP. Is there any way to customize the ip settings that are used ?

Thanks for your help

**Comment by govert** [comment]
This looks like a plan: https://forums.tomshardware.com/faq/how-to-change-default-internet-connection-sharing-ip-address-range.1606758/

**Comment by Moret84** [comment]
Thanks, you are the man.
